### ISSUE TITLE
Local data and OpenAI LLM no context.

### ISSUE THREAD

**Issue by vladaCizek** [ChunAllen/langchain-local#2]
Hi man, 

thanks for your example. I've tried it and I have to report, no matter what I query out of the scope of my local data, I always get bassically the same response: 'The context provided does not provide any information about the...', which simply indicates, we don't receive anything from openAI.

Could you please confirm, if this code still works, as intended? 

Thanks!

**Comment by mshafnas** [comment]
Did you get any solution for the above case?

**Comment by ChunAllen** [comment]
Hi @vladaCizek, would like to know if you tried cloning this repo to your local. 
If you add your text files inside `docs/` and run the command using 

```
node index.js "{{ your prompt related to the text files }}"
```

you should be able to get answers. 
**Note:**
- you need to provide OpenAI credentials in `.env`
- change the `.env.copy` to `.env`

**Comment by ChunAllen** [comment]
> Did you get any solution for the above case?

please refer also to my comment to @vladaCizek
